on: 

 push:
  
  paths: 
     - '~/gitPractice/Repository-for-Yamabuki/**.sh'
  branches:
    -main
   

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0

